language: ruby
rvm: 3.0.2

branches:
  only:
    - master

notifications:
  email:
    on_success: always
    on_failure : always

script:
 - gem update --system
 - gem install bundler
 - bundler update --bundler
 - gem install bundler -v 2.2.32
 - gem install jekyll -v 4.2.0
 - bundle exec jekyll build

deploy:
  provider: pages
  local_dir: _site/
  token: $TRAVIS_DEPLOY_TOKEN
  keep_history: false
  skip_cleanup: true
  target_branch: gh-pages
  fqdn: www.saifkhichi.com
  on:
    branch: master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
