remote_theme:              saifkhichi96/simple-material
baseurl:                   ''
url:                       https://www.saifkhichi.com
enforce_ssl:               https://www.saifkhichi.com
repository:                saifkhichi96/saifkhichi96.github.io

# Build settings
markdown: kramdown
plugins:
  - jekyll-email-protect

author:
  name: Saif Khan
  url: https://www.saifkhichi.com/

favicon:                   /favicon.ico
logo:                      /assets/images/logo.png

google_site_verification:  a756de613e3e91e14743d6a24b29a35c
google_adsense:            ca-pub-4333877529904422
# google_analytics:        UA-43339302-11
# google_analytics_ga4:    G-GABC1DEFG

# -----------------------------------------------------------------------------
# Site Navigation
# -----------------------------------------------------------------------------
menu_main:
  - title:                   Home
    icon:                    roofing
    url:                     /
  - title:                   My research
    icon:                    science
    url:                     /research/
  - title:                   Work with me
    icon:                    work
    url:                     /collaborate/



# Includes an icon in the footer for each username you enter
menu_social:
  email:                   saifkhichi96@gmail.com
  github:                  saifkhichi96
  linkedin:                saifkhichi96
  rss:                     rss
  stackoverflow:           4690466
  youtube:                 /channel/UCj4yPuKHi9pZ9WbKbfh5MEQ
  playconsole:             7722501168179136426


# Includes links to your site's privacy policy and terms of service in the footer
menu_footer:
  - title:                 'Cookies'
    url:                   '/cookie-policy/'
  - title:                 'Privacy Policy'
    url:                   '/privacy/'
  - title:                 'Terms of Service'
    url:                   '/terms/'

breadcrubms:               true
navigation_footer:         true
icons:                     true

# Enable commenting on posts
disqus:                    saifkhichi

# For showing Twitter cards
twitter:
  username: saifkhichi96

#
# !! You don't need to change any of the configuration flags below !!
#

collections:
  docs:
    output:                true
    permalink:             /docs/:path/
  pages:
    output:                true
    permalink:             /:title/
  projects:
    output:                true
    permalink:             /projects/:path/
  research:
    output:                true
    permalink:             /research/:path/
  collaboration:
    output:                true
    permalink:             /collaborate/:path/
  news:
    output:                true
    permalink:             /news/:year/:month/:day/:title/

defaults:
  - scope:
      path: ''
    values:
      license:
        content:
          name: Creative Commons Attribution 4.0 International License
          url: https://creativecommons.org/licenses/by/4.0/
        code:
          name: MIT License
          url: https://opensource.org/licenses/MIT/

installable:               true
