name: Generate PDF resume
on: page_build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages

      # Compile LaTex to PDF
      - name: Github Action for LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          latexmk_use_lualatex: true
          root_file: assets/cv/resume.tex
          work_in_root_file_dir: true

      # Upload new PDF to repository
      - name: Commit and Push new file
        run: |
          git config user.name "Saif Khan"
          git config user.email saifkhichi96@gmail.com
          git add assets/cv/resume.pdf
          git commit -C HEAD --amend
          git push --force
